brcmfmac: Remove array of functions
As per 'commit c9aa7a91de74 ("brcmfmac: Remove array of functions")'
replace the array of functions with a pair of pointers to the
relevant functions to fix the compilation errors.

drivers/net/wireless/broadcom/brcm80211/brcmfmac/bcmsdh.c: In function ‘brcmf_sdiod_probe’:
drivers/net/wireless/broadcom/brcm80211/brcmfmac/bcmsdh.c:920:15: error: ‘struct brcmf_sdio_dev’ has no member named ‘func’; did you mean ‘func1’?
  if (sdiodev->func[0]->device == SDIO_DEVICE_ID_CYPRESS_4373) {
               ^~~~
               func1
drivers/net/wireless/broadcom/brcm80211/brcmfmac/bcmsdh.c:924:37: error: ‘struct brcmf_sdio_dev’ has no member named ‘func’; did you mean ‘func1’?
  ret = sdio_set_block_size(sdiodev->func[2], f2_blksz);
                                     ^~~~
                                     func1
drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c: In function ‘brcmf_sdio_firmware_callback’:

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>