crypto: gcm: Fixed compilation error
As per commit 76c6739477fa ("crypto: gcm - move to generic async
completion"), make changes to fix the below compilation error.

crypto/gcm.c: In function ‘crypto_gcm_setkey’:
crypto/gcm.c:107:35: error: field ‘result’ has incomplete type
   struct crypto_gcm_setkey_result result ____cacheline_aligned;
                                   ^~~~~~
scripts/Makefile.build:303: recipe for target 'crypto/gcm.o' failed
make[1]: *** [crypto/gcm.o] Error 1
Makefile:1052: recipe for target 'crypto' failed

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>