PCI: imx: Replace of_pci_get_host_bridge_resources() with devm_of_pci_get_host_bridge_resources()
As per
'commit 5bd51b35c7cb ("PCI: Rework of_pci_get_host_bridge_resources() to
devm_of_pci_get_host_bridge_resources()")', make changes to fix the
compilation error.

drivers/pci/controller/dwc/pci-imx6.c: In function ‘imx6_pcie_probe’:
drivers/pci/controller/dwc/pci-imx6.c:1428:9: error: implicit declaration of function ‘devm_of_pci_get_host_bridge_resources’; did you mean ‘pci_get_host_bridge_device’? [-Werror=implicit-function-declaration]
   ret = devm_of_pci_get_host_bridge_resources(np, 0, 0xff, &res,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         pci_get_host_bridge_device
cc1: some warnings being treated as errors
scripts/Makefile.build:303: recipe for target 'drivers/pci/controller/dwc/pci-imx6.o' failed

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>