Revert "net: phy: adin1200: add support for PHY LED polarity inversion"
The commit uses a kernel api that does not exist, i.e.
"led_polarity_set" and uses undefined constants causing build errors:

  CC      drivers/net/phy/adin.o
In file included from ./include/linux/bitmap.h:9,
                 from ./include/linux/cpumask.h:12,
                 from ./include/linux/smp.h:13,
                 from ./include/linux/lockdep.h:14,
                 from ./include/linux/rcupdate.h:29,
                 from ./include/linux/rculist.h:11,
                 from ./include/linux/pid.h:5,
                 from ./include/linux/sched.h:14,
                 from ./include/linux/delay.h:23,
                 from drivers/net/phy/adin.c:9:
drivers/net/phy/adin.c: In function 'adin_led_polarity_set':
drivers/net/phy/adin.c:841:40: error: '__PHY_LED_MODES_NUM' undeclared (first use in this function)
  841 |         for_each_set_bit(mode, &modes, __PHY_LED_MODES_NUM) {
      |                                        ^~~~~~~~~~~~~~~~~~~
./include/linux/find.h:559:56: note: in definition of macro 'for_each_set_bit'
  559 |         for ((bit) = 0; (bit) = find_next_bit((addr), (size), (bit)), (bit) < (size); (bit)++)
      |                                                        ^~~~
drivers/net/phy/adin.c:841:40: note: each undeclared identifier is reported only once for each function it appears in
  841 |         for_each_set_bit(mode, &modes, __PHY_LED_MODES_NUM) {
      |                                        ^~~~~~~~~~~~~~~~~~~
./include/linux/find.h:559:56: note: in definition of macro 'for_each_set_bit'
  559 |         for ((bit) = 0; (bit) = find_next_bit((addr), (size), (bit)), (bit) < (size); (bit)++)
      |                                                        ^~~~
./include/linux/find.h:559:69: warning: left-hand operand of comma expression has no effect [-Wunused-value]
  559 |         for ((bit) = 0; (bit) = find_next_bit((addr), (size), (bit)), (bit) < (size); (bit)++)
      |                                                                     ^
drivers/net/phy/adin.c:841:9: note: in expansion of macro 'for_each_set_bit'
  841 |         for_each_set_bit(mode, &modes, __PHY_LED_MODES_NUM) {
      |         ^~~~~~~~~~~~~~~~
drivers/net/phy/adin.c:843:22: error: 'PHY_LED_ACTIVE_LOW' undeclared (first use in this function)
  843 |                 case PHY_LED_ACTIVE_LOW:
      |                      ^~~~~~~~~~~~~~~~~~
drivers/net/phy/adin.c: At top level:
drivers/net/phy/adin.c:1027:18: error: 'struct phy_driver' has no member named 'led_polarity_set'; did you mean 'led_blink_set'?
 1027 |                 .led_polarity_set = adin_led_polarity_set,
      |                  ^~~~~~~~~~~~~~~~
      |                  led_blink_set
drivers/net/phy/adin.c:1027:37: error: initialization of 'int (*)(struct phy_device *)' from incompatible pointer type 'int (*)(struct phy_device *, int,  long unsigned int)' [-Werror=incompatible-pointer-types]
 1027 |                 .led_polarity_set = adin_led_polarity_set,
      |                                     ^~~~~~~~~~~~~~~~~~~~~
drivers/net/phy/adin.c:1027:37: note: (near initialization for 'adin_driver[1].get_sset_count')
cc1: some warnings being treated as errors
make[5]: *** [scripts/Makefile.build:243: drivers/net/phy/adin.o] Error 1

This reverts commit 46c17cb20928a68362fa4fbce48043cb1376daf6.

Signed-off-by: Josua Mayer <josua@solid-run.com>