tty: serial: fsl_lpuart: Convert timers to use timer_setup()
As per commit e99e88a9d2b0 ("treewide: setup_timer() -> timer_setup()"),
convert timers to use timer_setup() function to fix the below
compilation error.

drivers/tty/serial/fsl_lpuart.c: In function ‘lpuart_startup’:
drivers/tty/serial/fsl_lpuart.c:1376:3: error: implicit declaration of function ‘setup_timer’; did you mean ‘setup_irq’? [-Werror=implicit-function-declaration]
   setup_timer(&sport->lpuart_timer, lpuart_timer_func,
   ^~~~~~~~~~~
   setup_irq
scripts/Makefile.build:303: recipe for target 'drivers/tty/serial/fsl_lpuart.o' failed

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>