ASoC: fsl: fixed compilation errors
In commit f31768349447 ("ASoC: fsl_ssi: Rename fsl_ssi_private to fsl_ssi")
So, renaming fsl_ssi_private to fsl_ssi to fix the below compilation error.

sound/soc/fsl/fsl_ssi.c: In function ‘fsl_ssi_imx_probe’:
sound/soc/fsl/fsl_ssi.c:1339:27: error: ‘np’ undeclared (first use in this function); did you mean ‘up’?
  if (of_property_read_u32(np, "fsl,dma-buffer-size", &buffer_size))
                           ^~
                           up
sound/soc/fsl/fsl_ssi.c:1339:27: note: each undeclared identifier is reported only once for each function it appears in
sound/soc/fsl/fsl_ssi.c:1342:7: error: ‘ssi_private’ undeclared (first use in this function); did you mean ‘PG_private’?
  if (!ssi_private->use_dma) {
       ^~~~~~~~~~~
       PG_private
scripts/Makefile.build:305: recipe for target 'sound/soc/fsl/fsl_ssi.o' failed
make[3]: *** [sound/soc/fsl/fsl_ssi.o] Error 1

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Srikanth Krishnakar <Srikanth_Krishnakar@mentor.com>